In [2]:
import numpy as np

元素乘法：np.multiply(a,b)

矩阵乘法：np.dot(a,b) 或 a.dot(b) 或 np.matmul(a,b) 或 a @ b

*，在 np.array 中重载为元素乘法，在 np.matrix 中重载为矩阵乘法

In [3]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [4]:
np.multiply(a,a)

array([[ 1,  4],
       [ 9, 16]])

In [5]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [6]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

---

In [7]:
A = np.mat(np.arange(1,5).reshape(2,2))
A

matrix([[1, 2],
        [3, 4]])

In [8]:
np.multiply(A,A)

matrix([[ 1,  4],
        [ 9, 16]])

In [9]:
A*A

matrix([[ 7, 10],
        [15, 22]])

In [10]:
A.dot(A)

matrix([[ 7, 10],
        [15, 22]])

In [11]:
predictions = np.array([0, 1, 1, 3, 2, 1, 7])
final_prediction = np.bincount(predictions).argmax()    # [1, 3, 1, 1, 0, 0, 0, 1] 1
final_prediction

array([1, 2, 2, 1, 0, 1], dtype=int64)

In [ ]:
# 创建一个一维数组
arr_1d = np.array([1, 2, 3, 4])

# 使用np.newaxis增加一个新维度
arr_2d = arr_1d[np.newaxis, :]

print("一维数组:")
print(arr_1d)
print(arr_1d.shape)
print("转化为二维数组:")
print(arr_2d)
print(arr_2d.shape)