原理上都适用于分类问题
- bce：二分类问题 （0-1）
    - 概率的过程通过 sigmoid
    - 1d(scalar) 的 output `logits` => 2d `[1-sigmoid(z), sigmoid(z)]`
- cross_entropy：多分类问题（`0, 1, 2, ... , C-1`）
    - 概率化的过程通过 softmax
    - log softmax

In [11]:
import torch
import torch.nn.functional as F
from torch import nn

In [12]:
# prediction
input = torch.randn(3, requires_grad=True)  # number of samples: 3
input

tensor([ 0.4767, -0.4485, -0.2553], requires_grad=True)

In [13]:
# GT
target = torch.empty(3, dtype=torch.long).random_(2)
target

tensor([1, 0, 0])

## F.binary_cross_entropy

F.binary_cross_entropy 的 target 可以是浮点数，未必非得是 0-1 (integer)
  - VAE 在图像重构时的 loss，通过 bce loss 定义和计算的；

In [14]:
loss = F.binary_cross_entropy(torch.sigmoid(input), target.to(torch.float))
loss

tensor(0.5168, grad_fn=<BinaryCrossEntropyBackward0>)

In [15]:
-torch.mean(target * torch.log(F.sigmoid(input)) + (1-target) * torch.log(1-F.sigmoid(input)))

tensor(0.5168, grad_fn=<NegBackward0>)

## nn.BCELoss

In [16]:
l = nn.BCELoss()
l(torch.sigmoid(input), target.to(torch.float))

tensor(0.5168, grad_fn=<BinaryCrossEntropyBackward0>)

## F.cross_entropy

- 1d => 2d

In [17]:
input_ = torch.stack([1-torch.sigmoid(input), torch.sigmoid(input)], dim=1)
# log softmax
input_ = torch.log(input_)
input_

tensor([[-0.9597, -0.4829],
        [-0.4938, -0.9423],
        [-0.5736, -0.8289]], grad_fn=<LogBackward0>)

In [18]:
F.nll_loss(input_, target)

tensor(0.5168, grad_fn=<NllLossBackward0>)